package console.enums;

public enum ConsoleState {

    NOT_STARTED,
    AUCTION_WATCHING,
    AUCTION_ASKING,
    AUCTION_HEARING,
    WAIT_FOR_DECLARER,
    DECLARE_SKAT,
    DECLARE_TRUMPTYPE,
    DECLARE_TRUMPCOLOR,
    PLAYING_YOUR_MOVE,
    PLAYING_NOT_YOUR_MOVE,
    GAME_FINISHED;

}
